### ISSUE TITLE
Is it possible to use an existing excel file?

### ISSUE THREAD

**Issue by piwonesien** [salvois/LargeXlsx#24]
Hey, 
is it possible to fill data into an existing excel file or starts this library always from scratch with an empty excel file?

So, could I do something like this?

```
File.Copy("Template.xlsx", "data.xlsx");
using var stream = new FileStream("data.xlsx", FileMode.Open, FileAccess.ReadWrite);
using var xlsxWriter = new XlsxWriter(stream);
xlsxWriter
    .BeginWorksheet("Sheet 1")
    .SkipRows(2); // Template headers

foreach(var row in datarows)
{
   xlsxWriter.BeginRow();
   foreach(var cell in row){
      xlsxWriter.Write(cell);
   }
}
````

**Comment by salvois** [comment]
Hello @piwonesien ,
unfortunately you can only create a new XLSX file from scratch using the LargeXlsx library.
This is because content is written to the file in order and without reading any content.
If you need to copy data from an existing Excel file, you may want to use a library such as ExcelDataReader to read content from a source file while writing content to a new file using LargeXlsx.
Hope this helps,
   Salvo
