### ISSUE TITLE
Support for Preserving Leading and Trailing Spaces

### ISSUE THREAD

**Issue by kishore3886** [salvois/LargeXlsx#58]
The LargeXlsx library appears to trim or visually ignore leading and trailing spaces when writing text values to Excel. This behavior causes issues when spaces are critical for preserving the integrity of the data, as they are either omitted in the Excel output or not rendered properly.

1. Use the XlsxWriter.Write method to write a string with leading or trailing spaces, such as:
    writer.Write("  Leading and Trailing Spaces  ");
2. Open the generated .xlsx file in Excel.
3. Observe that the spaces are either trimmed or not visually rendered, depending on Excel's interpretation of the cell content.

This issue is critical for scenarios where data integrity depends on preserving exact string formatting, including leading and trailing spaces.

**Comment by salvois** [comment]
Thanks for reporting @kishore3886 .
The library should add xml:space="preserve" where appropriate to support your scenario.

**Comment by kishore3886** [comment]
> Thanks for reporting @kishore3886 . The library should add xml:space="preserve" where appropriate to support your scenario.

Thank you for the response and clarification. Just to confirm, do you plan to implement the `xml:space="preserve"` fix in the library, or would you recommend we implement a workaround in the meantime? If the fix is planned, is there an estimated timeline for when it might be available? Additionally, if there’s any guidance on manually adding the attribute as a temporary workaround, we’d appreciate your input. Thank you for your support!

**Comment by salvois** [comment]
Hi @kishore3886 ,
I can't figure out immediate workarounds you can apply, sorry. I think the fix should be implemented into the library, because it otherwise does any required escaping. About an ETA, thanks for understanding that LargeXlsx is a free time project, so I'll try my best to provide a solution but I can't make promises about it (family and job issues come first!). While applying a fix may not be complicated per se, I want to make sure handling your corner case doesn't have excessive impact on performance.
Thanks,
   Salvo

**Comment by salvois** [comment]
Hi @kishore3886 , this has been released in version 1.11.
